site_name: HCBench
repo_url: https://compbioclub.github.io/HCBench
nav:
  - Home: index.md
  - Parsers:
      - Overview: parsers/index.md
      - CHISEL: parsers/chisel.md
      - Alleloscope: parsers/alleloscope.md
      - SIGNALS: parsers/signals.md
      - SEACON: parsers/seacon.md
      - CNRein: parsers/cnrein.md
  - HCBench-sim:
      - Overview: gtbench/index.md
    #   - clusterConsistency : gtbench/clusterConsistency.md
    #   - cloneSizebycluster : gtbench/cloneSizebycluster.md
    #   - cellprofile : gtbench/cellprofile.md
  - HCBench-real:
      - Overview: realbench/index.md
theme:
  name: material
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css
